import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta
          name="google-site-verification"
          content="bNE9gUivzDgja3PjbBF1CLxGtDMelObwns4TSFKvkbE"
        />
        <meta
          name="naver-site-verification"
          content="fb6e8d64dcd5d1b64d6af2d113b3b973578cea24"
        />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
